#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
staging: &staging
  app: finginie
  stack: cedar
  config: &staging_config
    AIRBRAKE_KEY                 : "d32bd5cf0a8135db0b96b89c0ce468f9"
    BLOG_URI                     : "http://finginie.github.com/commentary"
    BUNDLE_WITHOUT               : "development:test"
    DEPLOYHOOKS_CAMPFIRE_API_KEY : "3fd084ab0d34857c48ee0bd1534e2b39f2bc40d6"
    DEPLOYHOOKS_CAMPFIRE_MESSAGE : "{{user}} deployed {{app}} to {{url}}. source: https://github.com/FinGinie/{{app}}/tree/{{head}}"
    DEPLOYHOOKS_CAMPFIRE_ROOM    : "Builds and deploys"
    DEPLOYHOOKS_CAMPFIRE_SSL     : "1"
    DEPLOYHOOKS_CAMPFIRE_URL     : "finginie"
    DEPLOYHOOKS_HTTP_URL         : "http://airbrake.io/deploys.txt?deploy[rails_env]=staging&api_key=d32bd5cf0a8135db0b96b89c0ce468f9"
    FACEBOOK_KEY                 : "218506538203759"
    FACEBOOK_SECRET              : "60131991fc9d5faeb78a164789d22a3e"
    FINGINIE_KEY            : "a0dfee3532cf52d9e479eff18701f5420788be609c59ed0d5959cb18964f97df"
    FINGINIE_SECRET         : "9071834b8fcf9028d2cd2d46b0a715c585b1b833086c7e4d4dc7a3bcfe68b34c"
    MAINTENANCE_PAGE_URL         : "https://docs.google.com/a/finginie.com/spreadsheet/viewform?formkey=dFJaRjVMaTdSUml1TTlkWG9uaGdKNmc6MA"
    MONGOLAB_URI                 : "mongodb://heroku_app4427460:kcfr65imah2j5cumpcjql0tpot@ds033007.mongolab.com:33007/heroku_app4427460"
    POSTAGEAPP_API_KEY           : "WMXkyiNWwa0k1JMJVBGKe2ttBGlysgHa"
    RACK_ENV                     : "staging"
    RAILS_ENV                    : "staging"
    REDIS_URL                    : "redis://redistogo:2b89b00bbd027a6a3d5eecd059ef7d70@panga.redistogo.com:9105/"
    REDISTOGO_URL                : "redis://redistogo:2b89b00bbd027a6a3d5eecd059ef7d70@panga.redistogo.com:9105/"
    SENDGRID_PASSWORD            : "miqeakzq"
    SENDGRID_USERNAME            : "app1577177@heroku.com"
    SPREADSHEET_KEY              : "0Ak3raVCu_XPhdGxrZVRMSEdacm1WdVBveTd6a294NEE"
    SPREADSHEET_LOGIN            : "deploys@finginie.com"
    SPREADSHEET_PASSWORD         : "gedesh123"
    TZ                           : "Asia/Kolkata"

spare:
  <<: *staging
  app: immense-harbor-5702
  config:
    <<: *staging_config
    FINGINIE_KEY             : "c75928c1f5a2a376dba4c417ce63083d4c4d2433fe1d615d30dbeb4e64867b97"
    FINGINIE_SECRET          : "78566c4e0a3b375565ddda0e7f75b2f4a26d3000046c05abc3182a8334d851fd"

production:
  <<: *staging
  app: cold-planet-6262
  config:
    <<: *staging_config
    DEPLOYHOOKS_HTTP_URL         : "http://airbrake.io/deploys.txt?deploy[rails_env]=production&api_key=d32bd5cf0a8135db0b96b89c0ce468f9"
    FACEBOOK_KEY                 : "227202437375090"
    FACEBOOK_SECRET              : "38dd90840dc6d9a83a8e7578780ddbd8"
    GOOGLE_ANALYTICS             : "UA-12345678-1"
    FINGINIE_KEY            : "115714224b640202bdb03280c2549099fd455ea0b062cd7a76305c700a770b3b"
    FINGINIE_SECRET         : "d3ff0cc8d111ba368484aeeef23968559676daa87cc550544409a7d8d50acdd3"
    RACK_ENV                     : "production"
    RAILS_ENV                    : "production"
