#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
staging: &staging
  app: finginie
  stack: cedar
  config: &staging_config
    AIRBRAKE_KEY                 : "d32bd5cf0a8135db0b96b89c0ce468f9"
    BUNDLE_WITHOUT               : "development:test"
    DEPLOYHOOKS_CAMPFIRE_API_KEY : "3fd084ab0d34857c48ee0bd1534e2b39f2bc40d6"
    DEPLOYHOOKS_CAMPFIRE_MESSAGE : "{{user}} deployed {{app}} to {{url}}. source: https://github.com/FinGinie/{{app}}/tree/{{head}}"
    DEPLOYHOOKS_CAMPFIRE_ROOM    : "Builds and deploys"
    DEPLOYHOOKS_CAMPFIRE_SSL     : "1"
    DEPLOYHOOKS_CAMPFIRE_URL     : "finginie"
    DEPLOYHOOKS_HTTP_URL         : "http://airbrake.io/deploys.txt?deploy[rails_env]=staging&api_key=d32bd5cf0a8135db0b96b89c0ce468f9"
    FACEBOOK_KEY                 : "218506538203759"
    FACEBOOK_SECRET              : "60131991fc9d5faeb78a164789d22a3e"
    GOOGLE_KEY                   : "991503885080.apps.googleusercontent.com"
    GOOGLE_SECRET                : "wgBNGF4LH4K8X8zZeHruc3Pg"
    MAINTENANCE_PAGE_URL         : "https://docs.google.com/a/finginie.com/spreadsheet/viewform?formkey=dFJaRjVMaTdSUml1TTlkWG9uaGdKNmc6MA"
    MONGOLAB_URI                 : "mongodb://heroku_app4427460:kcfr65imah2j5cumpcjql0tpot@ds033007.mongolab.com:33007/heroku_app4427460"
    RACK_ENV                     : "staging"
    RAILS_ENV                    : "staging"
    REDIS_URL                    : "redis://redistogo:2b89b00bbd027a6a3d5eecd059ef7d70@panga.redistogo.com:9105/"
    REDISTOGO_URL                : "redis://redistogo:2b89b00bbd027a6a3d5eecd059ef7d70@panga.redistogo.com:9105/"
    SENDGRID_PASSWORD            : "miqeakzq"
    SENDGRID_USERNAME            : "app1577177@heroku.com"
    SPREADSHEET_KEY              : "0Ak3raVCu_XPhdG9pM3NIMF95eVZYYlpCcUx1OUQzSHc"
    SPREADSHEET_LOGIN            : "deploys@finginie.com"
    SPREADSHEET_PASSWORD         : "gedesh123"
    TZ                           : "Asia/Kolkata"

production:
  <<: *staging
  app: cold-planet-6262
  config:
    <<: *staging_config
    DEPLOYHOOKS_HTTP_URL         : "http://airbrake.io/deploys.txt?deploy[rails_env]=production&api_key=d32bd5cf0a8135db0b96b89c0ce468f9"
    FACEBOOK_KEY                 : "227202437375090"
    FACEBOOK_SECRET              : "38dd90840dc6d9a83a8e7578780ddbd8"
    GOOGLE_ANALYTICS             : "UA-12345678-1"
    GOOGLE_KEY                   : "924488085977.apps.googleusercontent.com"
    GOOGLE_SECRET                : "lWCmvtoikvhfXnB31PJAUsBT"
    RACK_ENV                     : "production"
    RAILS_ENV                    : "production"
