defaults: &defaults
  host: localhost
  port: 6379

development:
  <<: *defaults
  db: 0

test:
  <<: *defaults
  db: 1

staging:
  <<: *defaults

production:
  <% uri = URI.parse(ENV['REDISTOGO_URL'] || '') %>
  host: <%= uri.host %>
  port: <%= uri.port %>
  password: <%= uri.password %>
