require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example., :portfolio_id => net_position.portfolio.id
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NetPositionsController do

  let (:net_position) { create :net_position }
  let (:valid_attributes) { attributes_for :net_position }
  # This should return the minimal set of attributes required to create a valid
  # NetPosition. As you add validations to NetPosition, be sure to
  # update the return value of this method accordingly.

  describe "GET show" do
    it "assigns the requested net_position as @net_position" do
      get :show, :id => net_position.id.to_s, :portfolio_id => net_position.portfolio.id
      assigns(:net_position).should eq(net_position)
    end
  end

  describe "GET new" do
    it "assigns a new net_position as @net_position" do
      get :new, :portfolio_id => net_position.portfolio.id
      assigns(:net_position).should be_a_new(NetPosition)
    end
  end

  describe "GET edit" do
    it "assigns the requested net_position as @net_position" do
      get :edit, :id => net_position.id.to_s, :portfolio_id => net_position.portfolio.id
      assigns(:net_position).should eq(net_position)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NetPosition" do
        expect {
          post :create, :net_position => valid_attributes, :portfolio_id => net_position.portfolio.id
        }.to change(NetPosition, :count).by(1)
      end

      it "assigns a newly created net_position as @net_position" do
        post :create, :net_position => valid_attributes, :portfolio_id => net_position.portfolio.id
        assigns(:net_position).should be_a(NetPosition)
#assigns(:net_position).should be_persisted
      end

      it "redirects to the created net_position" do
        post :create, :net_position => valid_attributes, :portfolio_id => net_position.portfolio.id
#response.should redirect_to(portfolio_net_position_path(net_position.portfolio, NetPosition.last))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved net_position as @net_position" do
        # Trigger the behavior that occurs when invalid params are submitted
        NetPosition.any_instance.stub(:save).and_return(false)
        post :create, :net_position => {}, :portfolio_id => net_position.portfolio.id
        assigns(:net_position).should be_a_new(NetPosition)
      end

      pending "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NetPosition.any_instance.stub(:save).and_return(false)
        post :create, :net_position => {}, :portfolio_id => net_position.portfolio.id
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested net_position" do
        # Assuming there are no other net_positions in the database, this
        # specifies that the NetPosition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NetPosition.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => net_position.id, :net_position => {'these' => 'params'}, :portfolio_id => net_position.portfolio.id
      end

      it "assigns the requested net_position as @net_position" do
        put :update, :id => net_position.id, :net_position => valid_attributes, :portfolio_id => net_position.portfolio.id
        assigns(:net_position).should eq(net_position)
      end

      it "redirects to the net_position" do
        put :update, :id => net_position.id, :net_position => valid_attributes, :portfolio_id => net_position.portfolio.id
        response.should redirect_to(portfolio_net_position_path(net_position.portfolio, net_position))
      end
    end

    describe "with invalid params" do
      it "assigns the net_position as @net_position" do
        # Trigger the behavior that occurs when invalid params are submitted
        NetPosition.any_instance.stub(:save).and_return(false)
        put :update, :id => net_position.id.to_s, :net_position => {}, :portfolio_id => net_position.portfolio.id
        assigns(:net_position).should eq(net_position)
      end

      pending "re-renders the 'edit' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NetPosition.any_instance.stub(:save).and_return(false)
        put :update, :id => net_position.id.to_s, :net_position => {}, :portfolio_id => net_position.portfolio.id
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested net_position" do
      net_position
      expect {
        delete :destroy, :id => net_position.id.to_s, :portfolio_id => net_position.portfolio.id
      }.to change(NetPosition, :count).by(-1)
    end

    it "redirects to the net_positions list" do
      delete :destroy, :id => net_position.id.to_s, :portfolio_id => net_position.portfolio.id
      response.should redirect_to(portfolio_url(net_position.portfolio))
    end
  end

end
