require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OtherAssetsController do

  # This should return the minimal set of attributes required to create a valid
  # OtherAsset. As you add validations to OtherAsset, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all other_assets as @other_assets" do
      other_asset = OtherAsset.create! valid_attributes
      get :index
      assigns(:other_assets).should eq([other_asset])
    end
  end

  describe "GET show" do
    it "assigns the requested other_asset as @other_asset" do
      other_asset = OtherAsset.create! valid_attributes
      get :show, :id => other_asset.id.to_s
      assigns(:other_asset).should eq(other_asset)
    end
  end

  describe "GET new" do
    it "assigns a new other_asset as @other_asset" do
      get :new
      assigns(:other_asset).should be_a_new(OtherAsset)
    end
  end

  describe "GET edit" do
    it "assigns the requested other_asset as @other_asset" do
      other_asset = OtherAsset.create! valid_attributes
      get :edit, :id => other_asset.id.to_s
      assigns(:other_asset).should eq(other_asset)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OtherAsset" do
        expect {
          post :create, :other_asset => valid_attributes
        }.to change(OtherAsset, :count).by(1)
      end

      it "assigns a newly created other_asset as @other_asset" do
        post :create, :other_asset => valid_attributes
        assigns(:other_asset).should be_a(OtherAsset)
        assigns(:other_asset).should be_persisted
      end

      it "redirects to the created other_asset" do
        post :create, :other_asset => valid_attributes
        response.should redirect_to(OtherAsset.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved other_asset as @other_asset" do
        # Trigger the behavior that occurs when invalid params are submitted
        OtherAsset.any_instance.stub(:save).and_return(false)
        post :create, :other_asset => {}
        assigns(:other_asset).should be_a_new(OtherAsset)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OtherAsset.any_instance.stub(:save).and_return(false)
        post :create, :other_asset => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested other_asset" do
        other_asset = OtherAsset.create! valid_attributes
        # Assuming there are no other other_assets in the database, this
        # specifies that the OtherAsset created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OtherAsset.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => other_asset.id, :other_asset => {'these' => 'params'}
      end

      it "assigns the requested other_asset as @other_asset" do
        other_asset = OtherAsset.create! valid_attributes
        put :update, :id => other_asset.id, :other_asset => valid_attributes
        assigns(:other_asset).should eq(other_asset)
      end

      it "redirects to the other_asset" do
        other_asset = OtherAsset.create! valid_attributes
        put :update, :id => other_asset.id, :other_asset => valid_attributes
        response.should redirect_to(other_asset)
      end
    end

    describe "with invalid params" do
      it "assigns the other_asset as @other_asset" do
        other_asset = OtherAsset.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OtherAsset.any_instance.stub(:save).and_return(false)
        put :update, :id => other_asset.id.to_s, :other_asset => {}
        assigns(:other_asset).should eq(other_asset)
      end

      it "re-renders the 'edit' template" do
        other_asset = OtherAsset.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OtherAsset.any_instance.stub(:save).and_return(false)
        put :update, :id => other_asset.id.to_s, :other_asset => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested other_asset" do
      other_asset = OtherAsset.create! valid_attributes
      expect {
        delete :destroy, :id => other_asset.id.to_s
      }.to change(OtherAsset, :count).by(-1)
    end

    it "redirects to the other_assets list" do
      other_asset = OtherAsset.create! valid_attributes
      delete :destroy, :id => other_asset.id.to_s
      response.should redirect_to(other_assets_url)
    end
  end

end
