require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OtherLiabilitiesController do

  let (:other_liability) { create :other_liability }
  let (:valid_attributes) { attributes_for :other_liability }

  describe "GET index" do
    it "assigns all other_liabilities as @other_liabilities" do
      get :index
      assigns(:other_liabilities).should eq([other_liability])
    end
  end

  describe "GET show" do
    it "assigns the requested other_liability as @other_liability" do
      get :show, :id => other_liability.id.to_s
      assigns(:other_liability).should eq(other_liability)
    end
  end

  describe "GET new" do
    it "assigns a new other_liability as @other_liability" do
      get :new
      assigns(:other_liability).should be_a_new(OtherLiability)
    end
  end

  describe "GET edit" do
    it "assigns the requested other_liability as @other_liability" do
      get :edit, :id => other_liability.id.to_s
      assigns(:other_liability).should eq(other_liability)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OtherLiability" do
        expect {
          post :create, :other_liability => valid_attributes
        }.to change(OtherLiability, :count).by(1)
      end

      it "assigns a newly created other_liability as @other_liability" do
        post :create, :other_liability => valid_attributes
        assigns(:other_liability).should be_a(OtherLiability)
        assigns(:other_liability).should be_persisted
      end

      it "redirects to the created other_liability" do
        post :create, :other_liability => valid_attributes
        response.should redirect_to(OtherLiability.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved other_liability as @other_liability" do
        # Trigger the behavior that occurs when invalid params are submitted
        OtherLiability.any_instance.stub(:save).and_return(false)
        post :create, :other_liability => {}
        assigns(:other_liability).should be_a_new(OtherLiability)
      end

      pending "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OtherLiability.any_instance.stub(:save).and_return(false)
        post :create, :other_liability => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested other_liability" do
        # Assuming there are no other other_liabilities in the database, this
        # specifies that the OtherLiability created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OtherLiability.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => other_liability.id, :other_liability => {'these' => 'params'}
      end

      it "assigns the requested other_liability as @other_liability" do
        put :update, :id => other_liability.id, :other_liability => valid_attributes
        assigns(:other_liability).should eq(other_liability)
      end

      it "redirects to the other_liability" do
        put :update, :id => other_liability.id, :other_liability => valid_attributes
        response.should redirect_to(other_liability)
      end
    end

    describe "with invalid params" do
      it "assigns the other_liability as @other_liability" do
        # Trigger the behavior that occurs when invalid params are submitted
        OtherLiability.any_instance.stub(:save).and_return(false)
        put :update, :id => other_liability.id.to_s, :other_liability => {}
        assigns(:other_liability).should eq(other_liability)
      end

      pending "re-renders the 'edit' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OtherLiability.any_instance.stub(:save).and_return(false)
        put :update, :id => other_liability.id.to_s, :other_liability => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested other_liability" do
      other_liability
      expect {
        delete :destroy, :id => other_liability.id.to_s
      }.to change(OtherLiability, :count).by(-1)
    end

    it "redirects to the other_liabilities list" do
      delete :destroy, :id => other_liability.id.to_s
      response.should redirect_to(other_liabilities_url)
    end
  end

end
